### ISSUE TITLE
npm run build fails on Windows

### ISSUE THREAD

**Issue by emerick** [brave/https-everywhere-builder#5]
`npm run build` fails on a vanilla Windows 10 installation with the following error:

```
https-everywhere-builder\scripts\preloadHTTPSE.js:154
              throw err
              ^

Error: Command failed: zip -r httpse.leveldb.zip httpse.leveldb && tar -czf httpse.leveldb.tgz httpse.leveldb
'zip' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

It's probably due to a lack of zip/unzip utilities in a standard Windows install. Probably better to use an npm zip module if possible, for portability.

**Comment by cschanaj** [comment]
See #14
